/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Auth": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "AuthClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "EvaluationDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "EvaluationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "EvaluationsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "MainTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}